export enum SYMBOL_LIST {
  PENDING = 'SYMBOL_LIST_PENDING',
  FULFILLED = 'SYMBOL_LIST_FULFILLED',
  REJECTED = 'SYMBOL_LIST_REJECTED',
}

export enum GET_PAIR_DATA {
  PENDING = 'GET_PAIR_DATA_PENDING',
  FULFILLED = 'GET_PAIR_DATA_FULFILLED',
  REJECTED = 'GET_PAIR_DATA_REJECTED',
}

export enum PAIR_DATA {
  ADD = 'ADD_PAIR_DATA',
  DELETE = 'DELETE_PAIR_DATA',
};
